name: 'github actions build and deploy gh-pages'
on: 
  push:
    branches:
      - main  // 基于 master 分支，如果你的分支不是这个，请切换
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   // 使用 ubuntu 服务器
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master  // 引用别人的部署插件
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}   // 这里需要设置成你的 token
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          BUILD_SCRIPT: npm install && npm run docs:build
